version: '3.2'
services:
  web:
    container_name: development
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw
    command:
      - /bin/bash
      - -c
      - |
        npm i
        npm run dev
