version: '3.2'
services:
  web:
    container_name: production
    build:
      context: .
      dockerfile: ./docker/prod/dockerfiles/dockerfile_node
    restart: always
    ports:
      - 80:80
    networks:
      - internal
