version: '3.2'
services:
  web:
    container_name: base
    build:
      context: .
      dockerfile: ./docker/local/dockerfiles/dockerfile_node
    restart: always
    ports:
      - 1234:1234
    networks:
      - internal
