# build environment
FROM node:10 as build
WORKDIR /var/www/html
COPY package*.json ./
RUN npm install -qy
RUN npm i -g npm
COPY . .
RUN npm run prod


# production environment
FROM nginx:stable-alpine
COPY ./docker/prod/config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /var/www/html/dist /var/www/html/public
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
