# build environment
FROM node:10.15.3 as build
WORKDIR /var/www/html
COPY ./src ./src
COPY ./docker ./docker
COPY package*.json ./
COPY webpack*.js ./
RUN npm i && npm run prod

# production environment
FROM nginx:stable-alpine
COPY ./docker/prod/config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /var/www/html/dist /var/www/html/public
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]